export const ROOT_URL = 'http://localhost:1337/api'

export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR'
export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'

export const NEW_EVENT_ERROR = 'NEW_EVENT_ERROR'
export const NEW_EVENT_REQUEST = 'NEW_EVENT_REQUEST'
export const NEW_EVENT_SUCCESS = 'NEW_EVENT_SUCCESS'

export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
